### PR TITLE
Custom link handler

### PR DESCRIPTION
**Pull request by jmbuhr**
Based on the discussion in https://github.com/jakewvincent/mkdnflow.nvim/issues/10

This adds the ability to pass a user-defined lua function to internally transform the path of a link.
Where internally means that the link will be displayed and written in the document un-transformed but it's transformed version will be used for file-creation and navigation.

This is helpful for navigating e.g. a folder of files created by https://logseq.com/

Note: In logseq one can choose the way dates for journal entries are displayed. For example, if the option YYYY-MM-DD is choosed this config works:

```
    perspective = {
        priority = 'root',
        fallback = 'current',
        root_tell = ".git"
    },
    prefix = {
        evaluate = false,
        string = "./"
    },
    links = {
        style = 'wiki',
        implicit_extension = nil,
        transform = function(input)
            if input:match('%d%d%d%d%-%d%d%-%d%d') then
                return('journals/'..input:gsub("%-","_"))
            else
                return('pages/'..input)
            end
        end
    },
```

It can now succesfullly open pages in `pages`, even those created by logseq for zotero entries, which logseq puts as `pages/@...`, as well as journal pages in `journal`.

### CODE REVIEW

**Comment by jmbuhr** [comment]
I rebased it onto your main branch :)

**Comment by jakewvincent** [comment]
Thanks @jmbuhr! Looking forward to testing this out later today

**Review by jakewvincent — APPROVED** [review]
Thanks @jmbuhr, this is an elegant solution :)

**Comment by jakewvincent** [comment]
Just merged this into dev, which I'll merge into main soon when I'm sure the other recent updates are ready :)

**Comment by jakewvincent** [comment]
Just added an explicit transformation option to complement this feature! The old `prefix` config option will now be provided under `transform_explicit`.

**Pull request merged**
