### PR TITLE
Insert a new to-do item on to-do toggle in case it's not found

### PR DESCRIPTION
**Pull request by denolehov**
Hi @jakewvincent! Thank you for this beautiful plugin, `mkdnflow` was a missing piece in my dream setup of an Obsidian-compatible, full-blown `nvim`-based markdown KMS with [`zk`](https://github.com/mickael-menu/zk-nvim) ❤️ 

In my workflow, I heavily rely on to-do lists, and the functionality provided by `mkdnflow` is just superb! However, I have one (perhaps controversial) improvement to suggest: **insert a todo-list item in case it's not found on toggle**. 

It's tedious to constantly have to write a `- [ ] `. This PR allows to just navigate to a future to-do list item, and toggle it into existence (and transition it into a desired state) with one command, here's a little demo:

https://user-images.githubusercontent.com/4748206/229793220-70771cc0-9277-4eab-9156-29ea1d566626.mov

### CODE REVIEW

**Comment by jakewvincent** [comment]
Hi @denolehov, thanks for the idea! I do already have something similar implemented, which is that if you perform a to-do toggle on an ordinary list item, it will be converted to a to-do list item. I'm not fully opposed to extending this to work on lines that are not already a list item, but does this information change anything for you?

**Comment by denolehov** [comment]
What I like about to-do toggle creating a to-do (either from a regular list item or from a non-list line) is the consistency of behavior between the two variants. In both cases it takes something that wasn't a to-do and turns it into one. And, given that this action is behind a specific command, it's safe to assume that the action was deliberate.

And, if `:MkdnToggleToDo` was invoked by mistake, it is very cheap to [u]ndo. Manually typing the checkbox markdown or defining a custom keymap to handle this is more effort.

But at the same time I understand if you don't want to overextend the to-do toggle command's behavior. Especially given that the workaround is relatively straightforward, for example:

```lua
vim.api.nvim_buf_create_user_command(0, 'AltMkdnToggleToDo', function(_)
  local lists = require("mkdnflow.lists")
  local line = vim.api.nvim_get_current_line()

  if lists.hasListType(line) then
    -- turns a regular list item into a to-do, or toggles the to-do
    vim.cmd("MkdnToggleToDo")

  else
    -- but if the line is not a list item, turn it into an unchecked to-do
    local row, _ = unpack(vim.api.nvim_win_get_cursor(0))
    local to_do_not_started = require('mkdnflow').config.to_do.not_started
    vim.api.nvim_buf_set_text(0, row - 1, 0, row - 1, 0, { '- [' .. to_do_not_started .. '] ' })
  end

end, { desc = "Create a to-do or toggle it with `mkdnflow`'s :MkdnToggleToDo" })
```

**Comment by jakewvincent** [comment]
Hmm, I'm not sure I got my point across. You currently don't have to type in the checkbox markdown manually, as long as you've created an ordinary list item. If you have just a `*` or `-` or `+` (or a number followed by a `.`), doing a to-do toggle results in the checkbox markdown being inserted, and you can then toggle it.

In any case, what you're proposing is an additional convenience step, which I'm not against, especially considering that the command (or the default mapping) don't currently do anything if it's not invoked on a list item or a to-do list item. I'll check out your PR soon, probably this weekend.

**Comment by m-faith** [comment]
It would be nice to be able to turn non-list items into  todo checklist items :)

**Pull request merged**
